#!/usr/bin/python
import numpy as np 
import sys 
import matplotlib.pyplot as plt 
import matplotlib as mpl

def getFromFile(f):
    data=np.loadtxt(f)
    d=[]
    n=0
    for l in data:
	if l[1]==0:
       	    n+=1	
	    d.append([])
	d[n-1].append(l)
    print n
    return d 
def pCycle(d,l,c,lw):
    line,=plt.plot(d[1],d[0],label =l, color=c,linestyle='-')
    return line
def save(a,f):
    d=np.transpose(a)
    f = open(f,'w')
    for row in d:
        for line in row:
            f.write(str(line))
            f.write('\t')
        f.write('\n')
    f.close()
        

#Colors
color_sequence = ['k','b','k','darkviolet','c','darkred']
linestyle=['-','--']
labels = ('2C profile', '6C', '100th', '400th','800th')
# plot
plt.style.use('z')
mpl.rcParams['figure.subplot.left'] =0.15
mpl.rcParams['figure.subplot.right'] =0.95 
f = sys.argv[1]
data=getFromFile(f)
plt.figure()
ls='-'
i=0
n=0
lines=[]
for pdata in data:
    pd=np.array(pdata).transpose()
    lines.append(pCycle(pd,labels[i],color_sequence[i],1))
    n+=1
    i=int(n/2)
plt.ylim(-0.5,3.0)
plt.xlim(0,1.1*np.amax(np.loadtxt(f)[:,1]))
plt.ylabel('Voltage (V)')
plt.xlabel('Specific capacity ($mAh\cdot g^{-1}$)')
#plt.grid(True)
#plt.legend(lines[1::2],loc=2,framealpha=0.4)



sub_axes = plt.axes([0.3, 0.5, 0.38, 0.3])
i=0
n=0
lines=[]
for pdata in data:
    pd=np.array(pdata).transpose()
    sub_axes.plot(pd[1],pd[0],label =labels[n], color=color_sequence[i],linestyle='-')
    n+=1
    i=int(n/2)
plt.ylim(-0.1,0.1)
plt.xlim(0,300)
plt.xticks(np.linspace(0,300,3))
plt.yticks(np.linspace(-0.1,0.1,3))

plt.setp(sub_axes)
plt.savefig(f+'.pdf')
