#!/usr/bin/python
import numpy as np 
import sys 
import matplotlib.pyplot as plt 
import matplotlib as mpl
import matplotlib.ticker as mtick 


def getFromFile(f):
    data=np.loadtxt(f)
    d=[]
    n=0
    for l in data:
	if l[1]==0:
       	    n+=1	
	    d.append([])
	d[n-1].append(l)
    return d 
def pCycle(d,l,c,lw):
    line,=plt.plot(d[1],d[0],label =l, color=c,linestyle='-')
    return line
def save(a,f):
    d=np.transpose(a)
    f = open(f,'w')
    for row in d:
        for line in row:
            f.write(str(line))
            f.write('\t')
        f.write('\n')
    f.close()
        

#Colors
color_sequence = ['g','b','k','darkviolet','c','darkred']
linestyle=['-','--']
labels = ('2C', '6C', '100th', '400th','800th')



# plot
plt.style.use('z')
mpl.rcParams['figure.subplot.left'] =0.15
mpl.rcParams['figure.subplot.right'] =0.95 
f = sys.argv[1]
dA=np.loadtxt('1400p')
dP=np.loadtxt('1600p')


ax=plt.subplot(111)
pd=np.array(dP).transpose()
po=np.array(dA).transpose()

ax.plot(po[0],po[1],label ='PHC-1400', color='m',marker=('o'))
ax.plot(pd[0],pd[1],label ='PHC-1600', color='g',marker=('o'))



#ax.yaxis.set_major_formatter(mtick.FormatStrFormatter('%.1e'))
ax.set_xscale('log')
ax.set_yscale('log')
ax.invert_xaxis()



plt.ylabel('CSA ($m^2\cdot g^{-1}$)')
plt.xlabel('Pore width ($\AA$)')


plt.legend(loc=6,framealpha=0.4)
plt.savefig(f+'csa.pdf')
