#!/usr/bin/python
import numpy as np 
import sys 
import matplotlib.pyplot as plt 
import matplotlib as mpl
import matplotlib.ticker as mtick 


def getFromFile(f):
    data=np.loadtxt(f)
    d=[]
    n=0
    for l in data:
	if l[1]==0:
       	    n+=1	
	    d.append([])
	d[n-1].append(l)
    return d 
def pCycle(d,l,c,lw):
    line,=plt.plot(d[1],d[0],label =l, color=c,linestyle='-')
    return line
def save(a,f):
    d=np.transpose(a)
    f = open(f,'w')
    for row in d:
        for line in row:
            f.write(str(line))
            f.write('\t')
        f.write('\n')
    f.close()
        

#Colors
cs = ['g','b','k','darkviolet','c','darkred']
linestyle=['-','--']
labels = ('MAC1000', 'MAC1200', 'MAC1400', 'MAC1600','800th')



# plot
plt.style.use('z')
mpl.rcParams['figure.subplot.left'] =0.15
mpl.rcParams['figure.subplot.right'] =0.95 
fs = sys.argv[1:]
dA=[]
for f in fs:
    dA.append(np.loadtxt(f, skiprows= 1 ,delimiter = "," , usecols=(0,1,2) , dtype=float))

i=0
for d in dA:
    pd=np.array(d).transpose()
    plt.plot(pd[0]/pd[1],pd[2],label =labels[i], color=cs[i],marker=('o'))
    i+=1


#plt.xlim(0,1.1*np.amax(pd[0]))
#plt.ylim(-1,1.3*np.amax(pd[1]))
plt.ylim(0,20)
#plt.yscale('log')
plt.ylabel('Volume adsorbed ($cm^3\cdot g^{-1}$)')
plt.xlabel('Relative pressure ($P/P_o$)')

plt.legend(loc=5,framealpha=0.4)


plt.savefig('isothermo.pdf')
