#!/usr/bin/python
import numpy as np 
import sys 
import matplotlib.pyplot as plt 
import matplotlib as mpl
import matplotlib.ticker as mtick 


def getFromFile(f):
    data=np.loadtxt(f)
    d=[]
    n=0
    for l in data:
	if l[1]==0:
       	    n+=1	
	    d.append([])
	d[n-1].append(l)
    return d 
def pCycle(d,l,c,lw):
    line,=plt.plot(d[1],d[0],label =l, color=c,linestyle='-')
    return line
def save(a,f):
    d=np.transpose(a)
    f = open(f,'w')
    for row in d:
        for line in row:
            f.write(str(line))
            f.write('\t')
        f.write('\n')
    f.close()
        

#Colors
color_sequence = ['g','b','k','darkviolet','c','darkred']
linestyle=['-','--']
labels = ('2C', '6C', '100th', '400th','800th')



# plot
plt.style.use('z')
mpl.rcParams['figure.subplot.left'] =0.15
mpl.rcParams['figure.subplot.right'] =0.95 
f = sys.argv[1]
dA=np.loadtxt(f+'a')


pd=np.array(dA).transpose()
plt.plot(pd[0],pd[1],label ='Volume adsorbed', color='g',marker=('o'))



plt.xlim(0,1.1*np.amax(pd[0]))
plt.ylim(-1,1.3*np.amax(pd[1]))
#plt.ylim(0,1.8*np.amax(pd[1]))
plt.ylabel('Volume adsorbed ($cm^3\cdot g^{-1}$)')
plt.xlabel('Relative pressure ($P/P_o$)')

plt.legend(loc=2,framealpha=0.4)


plt.savefig(f+'.pdf')
