#!/usr/bin/python
import numpy as np
import sys
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
def pCycle(a,d,l,c):
    line,=a.plot(d[0],d[1],label =l, color=c,ls='o')
    return line
def save(a,f):
    d=np.transpose(a)
    f = open(f,'w')
    for row in d:
        for line in row:
            f.write(str(line))
            f.write('\t')
        f.write('\n')
    f.close()
        
def vecMinSca(v,s):
    o=[]
    for ve in v:
        o.append(ve-s)
    return o
#Colors
colors = ['g','b','k','darkviolet','c']
labels = ['PHC1000', 'PHC1200', 'PHC1400', 'PHC1600', '5th']
rates=['C/10','C/5','C/2','1C','2C','1C','C/2','C/5','C/10']
# plot

d=[]
for f in sys.argv[1:]:
    d.append(np.loadtxt(f).transpose())

fig=plt.figure(figsize=(6.5,5),dpi=600)
ax = fig.add_subplot(111)

ax.set_xlim(0,60)
ax.set_ylim(0,450)
ax.xaxis.set_major_locator(ticker.IndexLocator(5,-1))
ax.xaxis.set_minor_locator(ticker.IndexLocator(1,-1))
ax.set_ylabel('Capacity (mAh/g)')
ax.set_xlabel('Cycles')



i=0
for data in d:
    pCycle(ax,data,labels[i],colors[i])
    i=i+1
i=0
for r in rates:
    ax.text(3.5+5*i,400,r,ha='center')
    i=i+1

ax.legend(loc=4,framealpha=0.4)


ax.grid(True,c='0.5')

plt.savefig(f+'.pdf')
