#!/usr/bin/python
import numpy as np
import sys
import matplotlib.pyplot as plt
     
def getFromFile(f):
    data=np.loadtxt(f)
    d=[]
    n=0
    for l in data:
	if l[1]==0:
       	    n+=1	
	    d.append([])
	d[n-1].append(l)
    return d 
def pCycle(d,l,c,lw):
    line,=plt.plot(d[1],d[0],label =l, color=c,linestyle='-',linewidth=lw)
    return line
def save(a,f):
    d=np.transpose(a)
    f = open(f,'w')
    for row in d:
        for line in row:
            f.write(str(line))
            f.write('\t')
        f.write('\n')
    f.close()
        

#Colors
color_sequence = ['g','b','k','darkviolet','c']
linestyle=['-','--']
labels = ('1st', '2nd', '3rd', '4th', '5th')
# plot

f = sys.argv[1]
data=np.loadtxt(f).transpose()
fig, ax_c = plt.subplots()
ax_e = ax_c.twinx()

#plt.figure(figsize=(12,5))
ax_c.plot(data[0],data[1],label ='Charge capacity', color='r',linestyle='o',linewidth=1)
ax_c.plot(data[0],data[2],label ='Discharge capacity', color='b',linestyle='-',linewidth=1)
ax_e.plot(data[0],data[3],label ='Coulombic efficiency', color='k',linestyle='-',linewidth=1)

ax_c.set_ylim(0,140)
ax_e.set_ylim(0,120)
ax_c.set_ylabel('Capacity (mAh/g)')
ax_c.set_xlabel('Cycles')
ax_e.set_ylabel('Coulombic efficiency (%)')

plt.xlabel('Cycles')

plt.grid(True)
plt.legend(framealpha=0.4)
plt.savefig(f+'.pdf')
