#!/usr/bin/python
import numpy as np 
import sys 
import matplotlib.pyplot as plt 
import matplotlib as mpl
import matplotlib.ticker as mtick 

def getFromFile(f):
    of=open(f)
    d=of.readlines()[40:-2]
    of.close()
    print d
    return d

def pCycle(d,l,c,lw):
    line,=plt.plot(d[1],d[0],label =l, color=c,linestyle='-')
    return line
def save(a,f):
#    d=np.transpose(a)
    d=a
    f = open(f,'w')
    for row in d:
        f.write(row)
        f.write('\n')
    f.close()
def vecMinSca(v,s):
    o=[]
    for ve in v:
        o.append(ve-s)
    return o

       

#Colors
colors = ['g','b','darkviolet','darkred']
linestyle=['-','--']
labels = ('A', 'B', 'C', '400th','800th')



# plot
plt.style.use('z')
mpl.rcParams['figure.subplot.left'] =0.15
mpl.rcParams['figure.subplot.right'] =0.95 


# Read data
Xs = sys.argv[1:]
pPro=np.loadtxt('profile').transpose()

X=[]
for x in Xs:
    save(getFromFile(x),'temp')
    X.append(np.loadtxt('temp').transpose())

plt.plot(pPro[0],pPro[1],label ='Voltage profile', color='K', linewidth='1')
i=0
spots=np.loadtxt('profile')
pspots=[spots[60],spots[560],spots[840]]
for spo in pspots:
    plt.scatter(spo[0],spo[1], 50, color =colors[i])
    plt.text(spo[0],spo[1]-0.05,labels[i] , color =colors[i])
    i=i+1


plt.ylim(-0.15,0.5)
plt.xlim(14,30)
plt.ylabel('Voltage (V)')
plt.xlabel('Time (min)')
plt.legend(loc=2,framealpha=0.4)





sub_axes = plt.axes([0.35, 0.45, 0.45, 0.35])
i=1
v=X[0][1]+X[0][2]+X[0][3]+X[0][4]
sub_axes.plot(X[0][0],vecMinSca(v,1800),'-',label='A',lw=1,c=colors[0])

for x in X[1:]:
    sub_axes.plot(x[0],x[1]+x[2]+x[3]+[4],'-',label=labels[i],lw=1,c=colors[i])
    i=i+1

#plt.xticks(np.linspace(29.0,30.0,11))

#plt.xlim(28.5,30.5)
#plt.ylim(1200,1700)
#plt.xlim(1.1*np.amax(v),0)

sub_axes.set_ylabel('Intensity')
sub_axes.set_xlabel('$2 \Theta (^{\circ})$')
sub_axes.tick_params(labelleft='off')

plt.legend(loc=2,framealpha=0.4)








plt.setp(sub_axes)


plt.savefig('out.pdf')
