#!/usr/bin/python
import numpy as np
import sys
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import matplotlib as mpl
def getFromFile(f):
    data=np.loadtxt(f)
    d=[]
    n=0
    for l in data:
	if l[1]==0:
       	    n+=1	
	    d.append([])
	d[n-1].append(l)
    return d 
def pCycle(ax,d,l,c):
    line,=ax.plot(d[0],d[2],label =l, color=c,marker='o')
    return line
def pEff(ax,d,l,c):
    line,=ax.plot(d[0],d[3],label =l, color=c,marker='o')
    return line

def save(a,f):
    d=np.transpose(a)
    f = open(f,'w')
    for row in d:
        for line in row:
            f.write(str(line))
            f.write('\t')
        f.write('\n')
    f.close()
        

#Colors
colors = ['g','b','k','darkviolet','c']
labels = ['PHC1000', 'PHC1200', 'PHC1400', 'PHC1600', '5th']
# plot
plt.style.use('z') 
mpl.rcParams['figure.subplot.left'] =0.12
mpl.rcParams['figure.subplot.right'] =0.87 
d=[] 
for f in sys.argv[1:]:
    d.append(np.loadtxt(f).transpose())


fig=plt.figure()
ax_c = fig.add_subplot(111)


i=0
for data in d:
    pCycle(ax_c,data,labels[i],colors[i])
    i=i+1




ax_c.set_xlim(0,1.1*np.amax(d[0][0]))
ax_c.set_ylabel('Specific capacity ($mAh\cdot g^{-1}$)')
ax_c.set_xlabel('Cycle number')
plt.yticks(np.linspace(50,650,7))


ax_e = ax_c.twinx()


i=0
for data in d:
    pEff(ax_e,data,labels[i],colors[i])
    i=i+1


ax_e.legend(loc='upper center',bbox_to_anchor=(0.8,0.83),framealpha=0.4)
plt.yticks(np.linspace(0,110,12))
ax_e.set_ylabel('Coulombic efficiency (%)')

ax_e.set_xlim(0,70)


plt.savefig(f+'.pdf')
