#!/usr/bin/python
import numpy as np 
import sys 
import matplotlib.pyplot as plt 
def getFromFile(f):
    data=np.loadtxt(f)
    d=[]
    n=0
    for l in data:
	if l[1]==0:
       	    n+=1	
	    d.append([])
	d[n-1].append(l)
    return d 
def pCycle(d,l,c,lw):
    line,=plt.plot(d[1],d[0],label =l, color=c,linestyle='-',linewidth=lw)
    return line
def save(a,f):
    d=np.transpose(a)
    f = open(f,'w')
    for row in d:
        for line in row:
            f.write(str(line))
            f.write('\t')
        f.write('\n')
    f.close()
        

#Colors
color_sequence = ['g','b','k','darkviolet','c','darkred']
linestyle=['-','--']
labels = ('2C', '6C', '100th', '400th','800th')
# plot

f = sys.argv[1]
data=getFromFile(f)
plt.figure(figsize=(6,5),dpi=600)
ls='-'
i=0
n=0
lines=[]
for pdata in data:
    pd=np.array(pdata).transpose()
    lines.append(pCycle(pd,labels[i],color_sequence[i],1))
    n+=1
    i=int(n/2)
plt.ylim(-1.0,3.0)
plt.xlim(0,1.1*np.amax(np.loadtxt(f)[:,1]))
plt.ylabel('Voltage (V)')
plt.xlabel('Capacity (mAh/g)')
plt.grid(True)
plt.legend(lines[1::2],labels[:i],loc=2,framealpha=0.4,frameon=None)
plt.savefig(f+'.pdf')
