#!/usr/bin/python
import numpy as np
import sys
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import StringIO
def getFromFile(f):
    of=open(f)
    d=of.readlines()[40:-3]
    of.close()
    return d 
def pXRD(ax,i,d,l):
    line,=ax.plot(d[0],vecMinSca(d[1],-250*i))
    ax.text(8,d[1][0]+250*i,l)
#    ax.vlines(p,i,i+1.2,color=c,linestyles='--',lw=1)
#    ax.text(p-9,i+0.2,'$'+str(p)+'^{\circ}$',color=c)
#    ax.text(72,i+0.3,'R='+str(r),color=c)
    return line

def save(a,f):
    f = open(f,'w')
    for row in a:
        f.write(row)
    f.close()
        
def normalize(v):
    o=[]
    m=np.amax(v)
    for vr in v:
        o.append(vr/m)
    return o
def vecMinSca(v,s):
    o=[]
    for ve in v:
        o.append(ve-s)
    return o

#Colors
colors = ['g','b','k','darkviolet','c']
labels = ['PHC1000', 'PHC1200', 'PHC1400', 'PHC1600', '5th']
ps=[21.34,21.64,22.54,22.76]
R=[1.975,2.013,2.176,2.304]
# plot
plt.style.use('ggplot') 




da=[]
p=[]
for i in range(0,126,1):
    save(getFromFile(str(i)+'.JDX'),'temp')
    da.append(np.loadtxt('temp').transpose())
    p.append(str(i))
'''for f in sys.argv[1:]:
    save(getFromFile(f),'c'+f)
    da.append(np.loadtxt('c'+f).transpose())
    p.append(f[27:-4])'''
fig=plt.figure()
ax_c = fig.add_subplot(111)

print p
i=0
time=[]
pick0=[]
pick1=[]
pick2=[]
for d in da:

    pd=[d[0],(d[1]+d[2]+d[3]+d[4])/4]
    pick2.append(np.amax(pd[1][194:198]))
#    pXRD(ax_c,i,pd,p[i])
    i=i+1
    time.append((67+i)/3.0)
ax_c.plot(time,pick2,'r.',label='29.3')
 


ax_c.set_ylabel('Intensity')
ax_c.set_xlabel('time /h')
ax_c.tick_params(labelleft='off')

ax_c.legend(loc=4,framealpha=0.4)



plt.savefig('picks.pdf')
