#!/usr/bin/python
import numpy as np
import sys
import matplotlib.pyplot as plt
import matplotlib as mpl
import matplotlib.ticker as ticker
import StringIO
def getFromFile(f):
    of=open(f)
    d=of.readlines()[40:]
    of.close()
    return d 
def pXRD(i,d,l):
    colorc='k'
    lwc=0.2
    if i==97:
        colorc='g'
        lwc=1
    line,=plt.plot(d[0],vecMinSca(d[1],-50*i),c=colorc,lw=lwc)
#    ax.text(8,d[1][0]+250*i,l)
#    ax.vlines(p,i,i+1.2,color=c,linestyles='--',lw=1)
#    ax.text(p-9,i+0.2,'$'+str(p)+'^{\circ}$',color=c)
#    ax.text(72,i+0.3,'R='+str(r),color=c)
    return line

def save(a,f):
    f = open(f,'w')
    for row in a:
        f.write(row)
    f.close()
        
def normalize(v):
    o=[]
    m=np.amax(v)
    for vr in v:
        o.append(vr/m)
    return o
def vecMinSca(v,s):
    o=[]
    for ve in v:
        o.append(ve-s)
    return o

#Colors
colors = ['g','b','k','darkviolet','c']
labels = ['PHC1000', 'PHC1200', 'PHC1400', 'PHC1600', '5th']
ps=[21.34,21.64,22.54,22.76]
R=[1.975,2.013,2.176,2.304]

 
# plot 
plt.style.use('z') 
mpl.rcParams['figure.subplot.left'] =0.05 
mpl.rcParams['figure.subplot.right'] =0.95  



da=[]
p=[]
for i in range(0,67,1):
    save(getFromFile(str(i)+'.JDX'),'temp')
    da.append(np.loadtxt('temp').transpose())
    p.append(i)
for i in range(1,90,1):
    save(getFromFile('./67-/'+str(i)+'.JDX'),'temp')
    da.append(np.loadtxt('temp').transpose())
    p.append(i)

pPro=np.loadtxt('profile').transpose()

'''for f in sys.argv[1:]:
    save(getFromFile(f),'c'+f)
    da.append(np.loadtxt('c'+f).transpose())
    p.append(f[27:-4])'''

fig=plt.figure(figsize=(8,4),dpi=600)
grid_size = (1, 5)

plt.subplot2grid(grid_size, (0, 0), rowspan = 1, colspan = 3)

print p
i=0
for d in da:

    pd=[d[0],(d[1]+d[2]+d[3]+d[4])/4]
    pXRD(i,pd,str((66+p[i])/3.0)+'h')
    i=i+1

 


plt.xlim(10,60)
plt.ylim(np.amin(da[0][1]),i*50+2*np.amax(d[-1][1]))
plt.ylabel('Intensity')
plt.xlabel('$2 \Theta (^{\circ})$')
plt.tick_params(labelleft='off')


axd=plt.subplot2grid(grid_size, (0, 3), rowspan = 1, colspan = 1)
axd.plot(pPro[1],pPro[0],label ='Voltage profile', color='K', linewidth='1')

axd.set_ylim(0,np.amax(pPro[0]*1.1))
axd.set_xlim(-0.03,0.1)
#plt.ylim(np.amin(da[0][1]),i*50+2*np.amax(d[-1][1]))
axd.set_xlabel('Voltage (V)')
axd.set_ylabel('Time (h)')
axd.yaxis.tick_right()
axd.yaxis.set_label_position("right")
axd.set_xticks(np.arange(0,0.1,0.05))



ax=plt.subplot2grid(grid_size, (0, 4), rowspan = 1, colspan = 1)
ax.plot(pPro[1],pPro[0],label ='Voltage profile', color='K', linewidth='1')

ax.set_ylim(0,np.amax(pPro[0]*1.1))
ax.set_xlim(-0.3,3)
ax.set_xlabel('Voltage (V)')
ax.set_ylabel('Time (h)')
ax.yaxis.tick_right()
ax.yaxis.set_label_position("right")
ax.set_xticks(np.arange(0,3,1))



plt.savefig('out.pdf')
