#!/usr/bin/python
import numpy as np
import sys
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import matplotlib as mpl
def getFromFile(f):
    data=np.loadtxt(f)
    d=[]
    n=0
    for l in data:
	if l[1]==0:
       	    n+=1	
	    d.append([])
	d[n-1].append(l)
    return d 

def pChCap(ax,d,l,c): 
    line,=ax.plot(d[0],d[1],label =l+'Charge capacity',marker='s',**marker_style) 
    return line 
def pDisCap(ax,d,l,c): 
    line,=ax.plot(d[0],d[2],label =l+'Discharge capacity',marker='o',**marker_style) 
    return line 

def pEff(ax,d,l,c):
    line,=ax.plot(d[0],d[3],label =l+'Coulombic efficiency',marker='>',**marker_style) 
    return line

def save(a,f):
    d=np.transpose(a)
    f = open(f,'w')
    for row in d:
        for line in row:
            f.write(str(line))
            f.write('\t')
        f.write('\n')
    f.close()
        
marker_style = dict(linestyle='None',markeredgecolor='k', markevery=25,mew='1',markersize=5,fillstyle='none')
#Colors
colors = ['k','b','k','darkviolet','c']
labels = ['', '', 'PHC1400', 'PHC1600', '5th']
# plot
plt.style.use('z') 
mpl.rcParams['figure.subplot.left']=0.1
mpl.rcParams['figure.subplot.right']=0.9


d=[] 
for f in sys.argv[1:]:
    d.append(np.loadtxt(f).transpose())


fig=plt.figure(figsize=(8,3),dpi=600)
ax_c = fig.add_subplot(111)


i=0
for data in d:
#    pCycle(ax_c,data,labels[i],colors[i])
    pChCap(ax_c,data,labels[i],colors[i])
    pDisCap(ax_c,data,labels[i],colors[i])
    i=i+1




ax_c.set_xlim(0,1.1*np.amax(d[0][0]))
ax_c.set_ylim(0,140)
ax_c.set_ylabel('Specific capacity ($mAh\cdot g^{-1}$)')
ax_c.set_xlabel('Cycle number')
plt.yticks(np.linspace(20,140,7))

ax_c.legend(loc=3,framealpha=0.4)

ax_e = ax_c.twinx()


i=0
for data in d:
    pEff(ax_e,data,labels[i],colors[i])
    i=i+1


ax_e.legend(loc=4,framealpha=0.4)
ax_e.set_ylim(70,105)
plt.yticks(np.linspace(75,105,7))
ax_e.set_ylabel('Coulombic efficiency (%)')

ax_e.set_xlim(-20,1.1*np.amax(d[0][0]))


plt.savefig(f+'.pdf')
