#!/usr/bin/python
import numpy as np
import sys
import matplotlib.pyplot as plt
from matplotlib import style
     
def getFromFile(f):
    f = open(f)
    try:
        content = f.readlines( )
    finally:
        f.close( )

    d=[]
    for line in content[47:]:
        d.append([float(line.split(',')[0]),float(line.split(',')[1])])
    return d 

def save(a,f):
    d=np.transpose(a)
    f = open(f,'w')
    for row in d:
        for line in row:
            f.write(str(line))
            f.write('\t')
        f.write('\n')
    f.close()
        

#Colors
color_sequence = ['black','#660033','#336633','#CC9966','#993333']
linestyle=['-','--']
labels = ('1st', '2nd', '3rd', '4th', '5th')
# plot

f = sys.argv[1]
data=getFromFile(f)    
i=0
V=[]
I=[]
plt.figure(figsize=(5,4))
for d in data:
    V.append(d[0])
    I.append(1000*d[1]/((6.21-3.56)*0.95))
    if d[0]==2.5:
        ds=[V,I]
        save(ds,str(i))
        if i==0:
            ls=linestyle[0]
        else:
            ls=linestyle[1]
        plt.plot(V,I,label =labels[i], color=color_sequence[i],linestyle=ls,linewidth=1)
        V=[]
        I=[]
        i+=1
style.use('ggplot')
plt.ylabel('Current (A/g)' )
plt.xlabel('Voltage (V)')
plt.legend()
plt.xlim([-0.5,3.0])
plt.savefig(r'CV.pdf')
plt.show()
