#!/usr/bin/python
import numpy as np
import sys
import matplotlib.pyplot as plt
from matplotlib import style
import matplotlib as mpl     
def getFromFile(f):
    f = open(f)
    try:
        content = f.readlines( )
    finally:
        f.close( )

    d=[]
    for line in content[34:]:
        d.append([float(line.split(',')[0]),float(line.split(',')[1])])
    return d 

def save(a,f):
    d=np.transpose(a)
    f = open(f,'w')
    for row in d:
        for line in row:
            f.write(str(line))
            f.write('\t')
        f.write('\n')
    f.close()
        

#Colors
color_sequence = ['g','b','k','darkviolet','c','darkred']

linestyle=['-','--']
labels = ('1st', '2nd', '3rd', '4th', '5th')
# plot

plt.style.use('z')
mpl.rcParams['figure.subplot.left'] =0.20
mpl.rcParams['figure.subplot.right'] =0.95

f = sys.argv[1]
data=getFromFile(f)    
i=0
V=[]
I=[]
ax=plt.subplot(111)
lines=[]
for d in data:
    V.append(d[0])
    I.append(d[1])
    if d[0]==0:
        ds=[V,I]
        save(ds,str(i))
        lines.append(ax.plot(V,I,label =labels[i], color=color_sequence[i],linestyle='-',linewidth=2))
        V=[]
        I=[]
        i+=1
        print i
ax.yaxis.set_major_formatter(mpl.ticker.FormatStrFormatter('%.1e'))
ax.grid('on')
plt.ylabel('Current (A)' )
plt.xlabel('Voltage (V)')
plt.legend(loc=2)
plt.xlim([0,2.1])
plt.savefig(r'CV.pdf')
