#!/usr/bin/python
import numpy as np
import sys
import matplotlib.pyplot as plt
     
def getFromFile(f):
    data=np.loadtxt(f)
    d=[]
    n=0
    for l in data:
	if l[1]==0:
       	    n+=1	
	    d.append([])
	d[n-1].append(l)
    return d 
def pRaman(ax,d,l,c):
    line,=ax.plot(d[0],d[1],label =l, color=c,ls='-')
    return line
def pEff(ax,d,l,c):
    line,=ax.plot(d[0],d[3],label =l, color=c,marker='o')
    return line

def save(a,f):
    d=np.transpose(a)
    f = open(f,'w')
    for row in d:
        for line in row:
            f.write(str(line))
            f.write('\t')
        f.write('\n')
    f.close()
        

#Colors
colors = ['g','b','k','darkviolet','c']
labels = ['PHC1000', 'PHC1200', 'PHC1400', 'PHC1600', '5th']
# plot
 
d=[] 
for f in sys.argv[1:]:
    d.append(np.loadtxt(f).transpose())


fig=plt.figure(figsize=(6.5,5),dpi=600)
ax_c = fig.add_subplot(111)


i=0
for data in d:
    pRaman(ax_c,data,labels[i],colors[i])
    i=i+1




ax_c.set_xlim(800,1.1*np.amax(d[0][0]))
ax_c.set_ylabel('Intensity')
ax_c.set_xlabel('Raman shift ($cm^{-1}$)')
ax_c.legend(loc=1,framealpha=0.4)




plt.savefig(f+'.pdf')
