#!/usr/bin/python
import numpy as np
import sys
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
def pCycle(a,d,l,c):
    line,=a.plot(d[0],d[1],label ='Charge capacity', color='m' ,marker='o')
    line,=a.plot(d[0],d[2],label ='Discharge capacity', color='g' ,marker='o')
    return line
def save(a,f):
    d=np.transpose(a)
    f = open(f,'w')
    for row in d:
        for line in row:
            f.write(str(line))
            f.write('\t')
        f.write('\n')
    f.close()
        
def vecMinSca(v,s):
    o=[]
    for ve in v:
        o.append(ve-s)
    return o
#Colors
colors = ['g','b','k','darkviolet','c']
labels = ['PHC1000', 'PHC1200', 'PHC1400', 'PHC1600', '5th']
rates=['C/10','C/5','C/2','1C','2C']
# plot
plt.style.use('z')
d=[]
for f in sys.argv[1:]:
    d.append(np.loadtxt(f).transpose())

fig=plt.figure()
ax = fig.add_subplot(111)

ax.set_xlim(0,50)
ax.set_ylim(0,450)
ax.xaxis.set_major_locator(ticker.IndexLocator(5,0))
ax.set_ylabel('Specific capacity ($mAh\cdot g^{-1}$)')
ax.set_xlabel('Cycle number')



i=0
for data in d:
    pCycle(ax,data,labels[i],colors[i])
    i=i+1
i=0
for r in rates:
    ax.text(19+5*i,320-10*i,r,ha='center')
    i=i+1

#ax.text(37,150,'1C',ha='center')
ax.legend(loc=3,framealpha=0.4)

plt.tight_layout()

plt.savefig(f+'.pdf')
