#!/usr/bin/python
import numpy as np
import sys
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker

def getFromFile(f):
    data=np.loadtxt(f)
    d=[]
    n=0
    for l in data:
	if l[1]==0:
       	    n+=1	
	    d.append([])
	d[n-1].append(l)
    return d 
def pXRD(ax,i,d,l,c,p,r):
    line,=ax.plot(d[1],vecMinSca(normalize(d[2]),-1*i),label =l, color=c,ls='-',lw=2)
    ax.text(50,i+0.4,l,color=c)
    ax.vlines(p,i,i+1.2,color=c,linestyles='--',lw=1)
    ax.text(p-9,i+0.2,'$'+str(p)+'^{\circ}$',color=c)
    ax.text(72,i+0.3,'R='+str(r),color=c)
    return line

def save(a,f):
#    d=np.transpose(a)

    d=a
    f = open(f,'w')
    for row in d:
        for line in row:
            f.write(str(line))
            f.write('\t')
        f.write('\n')
    f.close()
        
def normalize(v):
    o=[]
    m=np.amax(v)
    for vr in v:
        o.append(vr/m)
    return o
def vecMinSca(v,s):
    o=[]
    for ve in v:
        o.append(ve-s)
    return o

#Colors
colors = ['g','b','k','darkviolet','c']
labels = ['PHC1000', 'PHC1200', 'PHC1400', 'PHC1600', '5th']
ps=[21.34,21.64,22.54,22.76]
R=[1.975,2.013,2.176,2.304]
# plot
plt.style.use('z') 
d=[]
for f in range(1,48,1):
    c=np.loadtxt(str(f)+'.ASC').transpose()
    d.append(c[1])
    print c[1]
dn=np.array(d)
save(dn,'out.txt')
