#!/usr/bin/python
import numpy as np
import sys
import matplotlib.pyplot as plt
     
def getFromFile(f):
    data=np.loadtxt(f)
    d=[]
    n=0
    for l in data:
	if l[1]==0:
       	    n+=1	
	    d.append([])
	d[n-1].append(l)
    return d 
def pCycle(d,l,c,lw):
    line,=plt.plot(d[1],d[0],label =l, color=c,linestyle='-',linewidth=lw)
    return line
def save(a,f):
    d=np.transpose(a)
    f = open(f,'w')
    for row in d:
        for line in row:
            f.write(str(line))
            f.write('\t')
        f.write('\n')
    f.close()
        

#Colors
color_sequence = ['g','b','k','darkviolet','c']
linestyle=['-','--']
labels = ('1st', '2nd', '3rd', '4th', '5th')
# plot

f = sys.argv[1]
data=np.loadtxt(f).transpose()

plt.figure(figsize=(6,5))
plt.subplot(411)
plt.plot(data[1],data[2],label =f, color='r',linestyle='-',linewidth=1)

plt.subplot(412)

plt.plot(data[1],data[2],label =f, color='r',linestyle='-',linewidth=1)
plt.xlabel('Cycles')
plt.ylabel('Intensity')

plt.legend(framealpha=0.4)
plt.savefig(f+'.pdf')
