#!/usr/bin/python
import datetime
import pyinotify
import logging
import os
import sys
from pyinotify import WatchManager, Notifier, ProcessEvent, IN_DELETE, IN_CREATE, IN_MODIFY

class EventHandler(ProcessEvent):
    global commd
    def process_IN_CREATE(self, event):
        print "Create file:%s." %os.path.join(event.path,event.name)
    def process_IN_DELETE(self, event):
        print "Delete file:%s." %os.path.join(event.path,event.name)
    def process_IN_MODIFY(self, event):
        print "Modify file:%s." %os.path.join(event.path,event.name)
	print commd
	os.system(commd)

def FsMonitor():
    wm = WatchManager()
    mask = IN_DELETE | IN_CREATE | IN_MODIFY
    notifier = Notifier(wm, EventHandler())
    wm.add_watch(sys.argv[1:],mask, auto_add= True, rec=True)
    print 'The watching begins...'
    notifier.process_events()
    notifier.loop()


commd=' '.join(sys.argv[1:])
FsMonitor()


